### ISSUE TITLE
Application payload Error.

### ISSUE THREAD

**Issue by hmuhdkamran** [mrellipse/toucan#10]
After updating the application, and generating a new build, It start an error on login,
`: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The payload was invalid.
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData) `

second when I use `dbContext.Database.ExecuteCommandAsync('Any procedure')` at first it work ok, and on next attempt It gives Database connection closed.

**Comment by mrellipse** [comment]
as you are hosting it on ubuntu, you will need to explicitly configure DataProtection similar to below

`public static partial class Extensions
    {
        public static void ConfigureDataProtection(this IServiceCollection services, Toucan.Server.Config config)
        {
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("/var/lib/toucan/web/keys"))
                .SetApplicationName(config.ApplicationName);
        }
    }    
`
otherwise the keys used to encrypt and decrypt token details will change each time the app is restarted. this is just a part of AspNetCore setup in general that developers need to learn about.

i haven't run into the other issue you mentioned regading database connection being closed. but I believe it might be a bug. can you try changing the StructureMap registrations to ContainerScoped()

* For<DbContextBase>().Use<MsSqlContext>() &
* All services in Cms.Service.ContainerRegistry

It might be that the default Transient registration is getting disposed of by garbage collection, and that is triggering the local connection pool to drop/close the underlying connection

**Comment by hmuhdkamran** [comment]
It has been resolved, 
the issue was that the folder have not sufficient rights, now it is working fine.
