### ISSUE TITLE
app..json not found

### ISSUE THREAD

**Issue by samdubey** [mrellipse/toucan#3]
D:\Workspace\toucan\src\server>dotnet run -p server.csproj -c Development

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'app..json' was not found and is not optional. The p
hysical path is 'D:\Workspace\toucan\src\server\app..json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Toucan.Server.WebApp.Main(String[] args) in D:\Workspace\toucan\src\server\Program.cs:line 15

**Comment by mrellipse** [comment]
I will check the readme docs - they must be out of date. Since I migrated the template to Asp.Net Core 2.0 it uses the framework environment variables. You should be okay if you run the following before starting the project up

set ASPNETCORE_ENVIRONMENT=Development
set ASPNETCORE_URLS=http://localhost:5000
dotnet run -p server.csproj

Just as an FYI - I am almost ready to deploy an update that is a fairly big one! It provides for proper I18n support, and also a lightweight 'pre-launch' app loading page (for mobile users on slow connections)

**Comment by mrellipse** [comment]
hi @samdubey i have updated docs, and release the new version last night (2.1.0)

if you run into any issues during install or setup of the latest version, just let me know and I will try to figure them out.

the yeoman generator worked okay for me from a fresh install
